[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_OPTIONS = "--max-old-space-size=4096"

# Handle client-side routing for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specific redirects for app routes - Next.js app router creates index.html in each directory
[[redirects]]
  from = "/auth/"
  to = "/auth/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/"
  to = "/dashboard/index.html"
  status = 200

[[redirects]]
  from = "/search/"
  to = "/search/index.html"
  status = 200

[[redirects]]
  from = "/bundles/"
  to = "/bundles/index.html"
  status = 200

[[redirects]]
  from = "/vendors/"
  to = "/vendors/index.html"
  status = 200

[[redirects]]
  from = "/deploy/"
  to = "/deploy/index.html"
  status = 200

[[redirects]]
  from = "/portfolios/"
  to = "/portfolios/index.html"
  status = 200

[[redirects]]
  from = "/forgot-password/"
  to = "/forgot-password/index.html"
  status = 200

[[redirects]]
  from = "/reset-password/"
  to = "/reset-password/index.html"
  status = 200

[[redirects]]
  from = "/tools/*/"
  to = "/tools/[id]/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"